### ISSUE TITLE
"EISDIR: illegal operation on a directory, read"

### ISSUE THREAD

**Issue by paul-hammant** [rigor789/nativescript-vue-ui-tests#5]
```
$ npm run android.screenshots
```

Yields:

```
> @ android.screenshots /scm/oss/nativescript-vue-ui-tests
> npm run appium -- --runType=android23


> @ appium /scm/oss/nativescript-vue-ui-tests
> node generate-screenshots.js "--runType=android23"

Search capabilities in /scm/oss/nativescript-vue-ui-tests/e2e/config/appium.capabilities.json
Found files: []
Search capabilities in /scm/oss/nativescript-vue-ui-tests
Found files: [ '/scm/oss/nativescript-vue-ui-tests/appium.capabilities.json',
  '/scm/oss/nativescript-vue-ui-tests/node_modules/nativescript-dev-appium/e2e/config/appium.capabilities.json',
  '/scm/oss/nativescript-vue-ui-tests/platforms/android/app/build/intermediates/assets/debug/app/tns_modules/nativescript-dev-appium/e2e/config/appium.capabilities.json',
  '/scm/oss/nativescript-vue-ui-tests/platforms/android/app/src/main/assets/app/tns_modules/nativescript-dev-appium/e2e/config/appium.capabilities.json' ]
fs.js:145
    throw err;
    ^

Error: EISDIR: illegal operation on a directory, read
    at Object.fs.readSync (fs.js:634:3)
    at tryReadSync (fs.js:474:20)
    at Object.fs.readFileSync (fs.js:515:19)
    at seCapabilities (/scm/oss/nativescript-vue-ui-tests/node_modules/nativescript-dev-appium/lib/capabilities-helper.js:51:23)
    at searchCapabilities (/scm/oss/nativescript-vue-ui-tests/node_modules/nativescript-dev-appium/lib/capabilities-helper.js:40:16)
    at Object.resolveCapabilities (/scm/oss/nativescript-vue-ui-tests/node_modules/nativescript-dev-appium/lib/capabilities-helper.js:10:39)
    at new NsCapabilities (/scm/oss/nativescript-vue-ui-tests/node_modules/nativescript-dev-appium/lib/ns-capabilities.js:17:50)
    at Object.<anonymous> (/scm/oss/nativescript-vue-ui-tests/node_modules/nativescript-dev-appium/index.js:31:24)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ appium: `node generate-screenshots.js "--runType=android23"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ appium script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/paul/.npm/_logs/2018-06-20T15_05_47_409Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ android.screenshots: `npm run appium -- --runType=android23`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ android.screenshots script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/paul/.npm/_logs/2018-06-20T15_05_47_457Z-debug.log
```

Contents of `/Users/paul/.npm/_logs/2018-06-20T15_05_47_409Z-debug.log` are:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/10.4.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'appium',
1 verbose cli   '--',
1 verbose cli   '--runType=android23' ]
2 info using npm@6.1.0
3 info using node@v10.4.1
4 verbose run-script [ 'preappium', 'appium', 'postappium' ]
5 info lifecycle @~preappium: @
6 info lifecycle @~appium: @
7 verbose lifecycle @~appium: unsafe-perm in lifecycle true
8 verbose lifecycle @~appium: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/scm/oss/nativescript-vue-ui-tests/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/scm/oss/nativescript-vue-ui-tests/node_modules/.bin:/usr/local/share/android-sdk/tools:/usr/local/share/android-sdk/tools/bin:/usr/local/share/android-sdk/platform-tools:/NotToBackup/flutter/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_172.jdk/Contents/Home/bin:/usr/local/opt/qt/bin:/Users/paul/Downloads/google-cloud-sdk/bin:/Users/paul/.rbenv/shims:/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin::/Users/paul/golang/bin:/usr/local/opt/go/libexec/bin:/usr/local/share/npm/bin:/Installed/chromedriver:/Users/paul/.rvm/bin:/Users/paul/golang/bin:/usr/local/opt/go/libexec/bin:/usr/local/share/npm/bin:/Installed/chromedriver:/Users/paul/.rvm/bin
9 verbose lifecycle @~appium: CWD: /scm/oss/nativescript-vue-ui-tests
10 silly lifecycle @~appium: Args: [ '-c', 'node generate-screenshots.js "--runType=android23"' ]
11 silly lifecycle @~appium: Returned: code: 1  signal: null
12 info lifecycle @~appium: Failed to exec appium script
13 verbose stack Error: @ appium: `node generate-screenshots.js "--runType=android23"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:961:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
14 verbose pkgid @
15 verbose cwd /scm/oss/nativescript-vue-ui-tests
16 verbose Darwin 17.6.0
17 verbose argv "/usr/local/Cellar/node/10.4.1/bin/node" "/usr/local/bin/npm" "run" "appium" "--" "--runType=android23"
18 verbose node v10.4.1
19 verbose npm  v6.1.0
20 error code ELIFECYCLE
21 error errno 1
22 error @ appium: `node generate-screenshots.js "--runType=android23"`
22 error Exit status 1
23 error Failed at the @ appium script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

I can't tell what is a directory that should be a file :-(

**Comment by rigor789** [comment]
Looks like there was a change in `nativescript-dev-appium`, but I'm not sure - will have to be investigated

**Comment by paul-hammant** [comment]
Cool - I'll watch this thread for updates :)

**Comment by rigor789** [comment]
Alright! This isn't a high priority right now, but I will try to get to it eventually!
